// Centralized UI copy — calm, direct, human voice
export const COPY = {
  errors: {
    generic:       "Quelque chose s'est mal passé. Réessaie.",
    save:          "L'enregistrement a échoué. Réessaie.",
    archive:       "Impossible d'archiver cette habitude.",
    deleteGoal:    "Impossible de supprimer cet objectif.",
    addMember:     (name: string) => `Aucun compte avec le pseudo « ${name} ».`,
    removeMember:  "Impossible de retirer ce membre.",
    leaveGroup:    "Impossible de quitter ce groupe.",
    deleteGroup:   "Impossible de supprimer ce groupe.",
    updateUsername:"Ce pseudo est peut-être déjà pris.",
    reaction:      "La réaction n'a pas pu être envoyée.",
  },
  success: {
    usernameUpdated: "Pseudo mis à jour.",
    memberAdded:     (name: string) => `${name} a rejoint le groupe.`,
    memberRemoved:   (name: string) => `${name} a été retiré.`,
  },
  empty: {
    habits:             "Aucune habitude",
    habitsHint:         "Crée ta première habitude pour commencer.",
    habitsCta:          "Lance-toi !",
    habitsCtaHint:      "Crée ta première habitude avec le bouton ci-dessus.",
    goals:              "Aucun objectif en cours",
    goalsHint:          "Définis un premier objectif avec le bouton ci-dessus.",
    badges:             "Aucun badge pour l'instant",
    badgesHint:         "Continue tes habitudes pour débloquer des récompenses.",
    activity:           "Tes journées validées apparaîtront ici.",
    circle:             "Ton cercle avance en silence pour l'instant",
    circleHint:         "Quand tes amis boucleront une journée ou atteindront un objectif, leurs progrès apparaîtront ici.",
    notifications:      "Tout calme pour l'instant",
    notificationsHint:  "Tes amis te soutiendront bientôt.",
    leaderboard:        "Personne n'a encore de score — à toi de lancer la machine.",
  },
  confirm: {
    archiveHabit:   "Archiver cette habitude ?",
    deleteGoal:     "Supprimer cet objectif ?",
    deleteGroup:    (name: string) => `Supprimer « ${name} » ?`,
    deleteGroupBody:"Cette action est définitive. Le groupe et ses habitudes communes seront supprimés pour tous les membres.",
    yes:            "Confirmer",
    cancel:         "Annuler",
  },
} as const;
